export const FETCH_PRODUCTS_START = 'products/FETCH_PRODUCTS_START';
export const FETCH_PRODUCTS_OK = 'products/FETCH_PRODUCTS_OK';
export const FETCH_PRODUCTS_ERROR = 'products/FETCH_PRODUCTS_ERROR';