export const routes = {
    admin: '/admin',
    home: '/',
    productID: '/product/:id',
    adminProductID: '/admin/product/:id',
    productEditID: '/admin/product/edit/:id',
    productAdd: '/admin/product/add',
    cart:'/cart',
    contact:'/contact',
    termsandconditions:'/termsandconditions',
    privacypolicy:'/privacypolicy',
    about: '/about',
    login:'/login',
    restore: '/restore',
    register:'/register',
}